import schedule
import time
from pipeline import run_pipeline  

'''
----------------------------------------

File to run the pipeline daily
(Generated by ChatGPT)

----------------------------------------

'''

# Define job (running pipeline)
def job():
    print("Running workout pipeline...")
    run_pipeline()
    print("Done!")

# Schedule to run every day at 6:00 AM
schedule.every().day.at("06:00").do(job)

print("Scheduler started...")
while True:
    schedule.run_pending()
    time.sleep(60)
